spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  #文件上传的相关设置
  servlet:
    multipart:
      enabled: true #默认为true
      max-file-size: 10MB #设置单个文件的上传大小
      max-request-size: 30MB #设置上传文件的总大小

#配置mybatis配置
mybatis:
  type-aliases-package: phonestore.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
pagehelper:
  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 8080
  ip: 127.0.0.1




